import React, { createContext } from "react";

export const langs = {
	ptbr: {
		"lang-code": "PT-BR",
		"lang-name-ptbr": "Português brasileiro",
		"lang-name-en": "Inglês Estados Unidos",
		"new": "Novo",
		"add": "Adicionar",
		"type": "Digite",
		"submit": "Enviar",
		"filter": "Filtrar",
		"change": "Trocar",
		"previous": "Anterior",
		"counter": "Contador",
		"the": "o",
		"is": "é",
		"user": "Usuário",
		"name": "Nome",
		"lastname": "Sobrenome",
		"username": "Usuário",
		"email": "E-mail",
		"password": "Senha",
		"country": "País",
		"city": "Cidade",
		"state": "UF",
		"address": "Endereço",
		"item": "Item",
		"items": "Items",
		"no-items-filter": "Nenhum item corresponde ao filtro.",
		"user-name": "Nome do usuário"
	},
	en: {
		"lang-code": "EN",
		"lang-name-ptbr": "Brazilian portuguese",
		"lang-name-en": "USA english",
		"new": "New",
		"add": "Add",
		"type": "Type",
		"submit": "Submit",
		"filter": "Filter",
		"change": "Change",
		"previous": "Previous",
		"counter": "Counter",
		"the": "the",
		"is": "is",
		"user": "User",
		"name": "Name",
		"lastname": "Last name",
		"username": "Username",
		"email": "E-mail",
		"password": "Password",
		"country": "Country",
		"city": "City",
		"state": "state",
		"address": "Address",
		"item": "Item",
		"items": "Items",
		"no-items-filter": "No items match the filter.",
		"user-name": "User name"
	},
};

export const LangContext = createContext([langs.ptbr, () => {}]);